Mykennel/Controllers/DogsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Mykennel.Data;
using Mykennel.Models;
using Mykennel.Utility;

namespace Mykennel.Controllers
{
    public class DogsController : Controller
    {
        private readonly ApplicationDbContext _context;
        // Szükséges a képek mappa eléréséhez
        private readonly IWebHostEnvironment _hostEnvironment;

        public DogsController(ApplicationDbContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            _hostEnvironment = hostEnvironment;
        }

        // GET: Dogs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dog = await _context.Dogs
                .Include(d => d.Breed)
                .Include(d => d.Father)
                .Include(d => d.Kennel)
                .Include(d => d.Kennel.ApplicationUser)
                .Include(d => d.Mother)
                .Where(l => l.Kennel.ApplicationUser.LockoutEnd < DateTime.Now || l.Kennel.ApplicationUser.LockoutEnd == null)
                .FirstOrDefaultAsync(m => m.DogId == id);
            if (dog == null)
            {
                return NotFound();
            }

            return View(dog);
        }

        // GET: Dogs/MyDogs
        public IActionResult MyDogs()
        {
            if (GetUserKennel() != null)
            {
                var userDogs = GetUserDogs();

                return View(userDogs);
            }
            TempData["ErrorMessage"] = "You need to create a kennel first!";
            return RedirectToAction("Settings", "Kennels");
        }

        // GET: Dogs/Create
        [Authorize(Roles = SD.Role_User_Breeder)]
        public IActionResult Create()
        {
            ViewData["BreedId"] = new SelectList(_context.Breeds, "BreedId", "Name");
            ViewData["FatherId"] = new SelectList(_context.Dogs.Where(m => m.KennelId == GetUserKennel().KennelId), "DogId", "Name");
            ViewData["KennelId"] = new SelectList(_context.Kennels.Where(m => m.KennelId == GetUserKennel().KennelId), "KennelId", "KennelName");
            ViewData["MotherId"] = new SelectList(_context.Dogs.Where(m => m.KennelId == GetUserKennel().KennelId), "DogId", "Name");
            return View();
        }

        // POST: Dogs/Create
        [Authorize(Roles = SD.Role_User_Breeder)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DogId,RegNumber,Born,Name,Sex,Description,TitlesGenetics,Status,DogImage,BreedId,KennelId,FatherId,MotherId")] Dog dog)
        {
            if (ModelState.IsValid)
            {         
                
                string webRootPath = _hostEnvironment.WebRootPath;
                var file = HttpContext.Request.Form.Files;
                // Ha lett kép kiválasztva, akkor csinálni kell valamit
                if (file.Count > 0)
                {
                    // útvonal, fájlnév, kiterjesztés összerakása
                    string fileName = dog.DogId.ToString() + "_" + Guid.NewGuid().ToString();
                    string kennelFolder = Path.Combine("kennels", dog.KennelId.ToString(), "dogs");
                    string uploadFolder = Path.Combine(webRootPath, kennelFolder);
                    string extension = Path.GetExtension(file[0].FileName);

                    // Mappa létrehozása ha nem létezik
                    if (!Directory.Exists(uploadFolder))
                    {
                        Directory.CreateDirectory(uploadFolder);
                    }

                    // Kép mentése FileStream-el
                    using (var fStream = new FileStream(Path.Combine(uploadFolder, fileName + extension), FileMode.Create))
                    {
                        file[0].CopyTo(fStream);
                    }
                    dog.DogImage = @"\" + Path.Combine(kennelFolder, fileName + extension);
                }

                _context.Add(dog);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(MyDogs));
            }
            ViewData["BreedId"] = new SelectList(_context.Breeds, "BreedId", "Name", dog.BreedId);
            ViewData["FatherId"] = new SelectList(_context.Dogs.Where(m => m.KennelId == GetUserKennel().KennelId), "DogId", "Name", dog.FatherId);
            ViewData["KennelId"] = new SelectList(_context.Kennels.Where(m => m.KennelId == GetUserKennel().KennelId), "KennelId", "KennelName");
            ViewData["MotherId"] = new SelectList(_context.Dogs.Where(m => m.KennelId == GetUserKennel().KennelId), "DogId", "Name", dog.MotherId);
            return View(dog);
        }

        // GET: Dogs/Edit/5
        [Authorize(Roles = SD.Role_User_Breeder)]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dog = await _context.Dogs.FindAsync(id);
            if (dog == null || dog.KennelId != GetUserKennel().KennelId)
            {
                return NotFound();
            }

            ViewData["BreedId"] = new SelectList(_context.Breeds, "BreedId", "Name", dog.BreedId);
            ViewData["FatherId"] = new SelectList(_context.Dogs.Where(m => m.KennelId == GetUserKennel().KennelId), "DogId", "Name", dog.FatherId);
            ViewData["KennelId"] = new SelectList(_context.Kennels.Where(m => m.KennelId == GetUserKennel().KennelId), "KennelId", "KennelName");
            ViewData["MotherId"] = new SelectList(_context.Dogs.Where(m => m.KennelId == GetUserKennel().KennelId), "DogId", "Name", dog.MotherId);
            return View(dog);
        }

        // POST: Dogs/Edit/5
        [Authorize(Roles = SD.Role_User_Breeder)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DogId,RegNumber,Born,Name,Sex,Description,TitlesGenetics,Status,DogImage,BreedId,KennelId,FatherId,MotherId")] Dog dog)
        {
            if (id != dog.DogId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    string webRootPath = _hostEnvironment.WebRootPath;
                    var file = HttpContext.Request.Form.Files;
                    // Ha lett kép kiválasztva, akkor csinálni kell valamit
                    if (file.Count > 0)
                    {
                        string fileName = dog.DogId.ToString() + "_" + Guid.NewGuid().ToString();
                        string kennelFolder = Path.Combine("kennels", dog.KennelId.ToString(), "dogs");
                        string uploadFolder = Path.Combine(webRootPath, kennelFolder); //összerakjuk az útvonalat hogy hova mentse
                        string extension = Path.GetExtension(file[0].FileName);

                        // Ha volt már kép, akkor ki kell törölni a régit
                        if (dog.DogImage != null)
                        {
                            var imagePath = Path.Combine(webRootPath, dog.DogImage.TrimStart('\\'));
                            if (System.IO.File.Exists(imagePath))
                            {
                                System.IO.File.Delete(imagePath);
                            }
                        }

                        if (!Directory.Exists(uploadFolder))
                        {
                            Directory.CreateDirectory(uploadFolder);
                        }

                        using (var fStream = new FileStream(Path.Combine(uploadFolder, fileName + extension), FileMode.Create))
                        {
                            file[0].CopyTo(fStream);
                        }
                        dog.DogImage = @"\" + Path.Combine(kennelFolder, fileName + extension);
                    }

                    _context.Update(dog);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DogExists(dog.DogId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(MyDogs));
            }
            ViewData["BreedId"] = new SelectList(_context.Breeds, "BreedId", "Name", dog.BreedId);
            ViewData["FatherId"] = new SelectList(_context.Dogs.Where(m => m.KennelId == GetUserKennel().KennelId), "DogId", "Name", dog.FatherId);
            ViewData["KennelId"] = new SelectList(_context.Kennels.Where(m => m.KennelId == GetUserKennel().KennelId), "KennelId", "KennelName");
            ViewData["MotherId"] = new SelectList(_context.Dogs.Where(m => m.KennelId == GetUserKennel().KennelId), "DogId", "Name", dog.MotherId);
            return View(dog);
        }

        // GET: Dogs/Delete/5
        [Authorize(Roles = SD.Role_User_Breeder)]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dog = await _context.Dogs
                .Include(d => d.Breed)
                .Include(d => d.Father)
                .Include(d => d.Kennel)
                .Include(d => d.Mother)
                .FirstOrDefaultAsync(m => m.DogId == id);
            if (dog == null || dog.KennelId != GetUserKennel().KennelId)
            {
                return NotFound();

Mykennel/Controllers/PuppiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Mykennel.Data;
using Mykennel.Models;
using Mykennel.Utility;

namespace Mykennel.Controllers
{
    public class PuppiesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PuppiesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Puppies/MyPuppies
        public IActionResult MyPuppies()
        {
            var userKennel = GetUserKennel();

            if (userKennel == null)
            {
                TempData["ErrorMessage"] = "You need to create a kennel first!";
                return RedirectToAction("Settings", "Kennels");
            }

            if (_context.Litters.Where(m => m.KennelId == userKennel.KennelId).Count() < 1)
            {
                TempData["ErrorMessage"] = "You need to have at least 1 litter to add puppies!";
                return RedirectToAction("MyLitters", "Litters");
            }

            var userPuppies = GetUserPuppies();
            return View(userPuppies);
        }

        // GET: Puppies/Create
        [Authorize(Roles = SD.Role_User_Breeder)]
        public IActionResult Create()
        {
            int userKennelId = GetUserKennel().KennelId;
            ViewData["DogId"] = new SelectList(_context.Dogs.Where(m => m.KennelId == userKennelId), "DogId", "Name");
            ViewData["LitterId"] = new SelectList(_context.Litters.Where(m => m.KennelId == userKennelId), "LitterId", "Name");
            return View();
        }

        // POST: Puppies/Create
        [Authorize(Roles = SD.Role_User_Breeder)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PuppyId,Name,Sex,Bookable,Aim,Description,DogId,LitterId")] Puppy puppy)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Add(puppy);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(MyPuppies));
                }
                catch (Exception)
                {
                    TempData["ErrorMessage"] = "You need to have a litter before you can add puppies!";
                    return RedirectToAction(nameof(Create));
                }
            }
            int userKennelId = GetUserKennel().KennelId;
            ViewData["DogId"] = new SelectList(_context.Dogs.Where(m => m.KennelId == userKennelId), "DogId", "Name", puppy.DogId);
            ViewData["LitterId"] = new SelectList(_context.Litters.Where(m => m.KennelId == userKennelId), "LitterId", "Name", puppy.LitterId);
            return View(puppy);
        }

        // GET: Puppies/Edit/5
        [Authorize(Roles = SD.Role_User_Breeder)]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var puppy = await _context.Puppies
                .Include(p => p.Dog)
                .Include(p => p.Litter)
                .FirstOrDefaultAsync(m => m.PuppyId == id);
            if (puppy == null || puppy.Litter.KennelId != GetUserKennel().KennelId)
            {
                return NotFound();
            }
            int userKennelId = GetUserKennel().KennelId;
            ViewData["DogId"] = new SelectList(_context.Dogs.Where(m => m.KennelId == userKennelId), "DogId", "Name", puppy.DogId);
            ViewData["LitterId"] = new SelectList(_context.Litters.Where(m => m.KennelId == userKennelId), "LitterId", "Name", puppy.LitterId);
            return View(puppy);
        }

        // POST: Puppies/Edit/5
        [Authorize(Roles = SD.Role_User_Breeder)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PuppyId,Name,Sex,Bookable,Aim,Description,DogId,LitterId")] Puppy puppy)
        {
            if (id != puppy.PuppyId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(puppy);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PuppyExists(puppy.PuppyId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(MyPuppies));
            }
            int userKennelId = GetUserKennel().KennelId;
            ViewData["DogId"] = new SelectList(_context.Dogs.Where(m => m.KennelId == userKennelId), "DogId", "Name", puppy.DogId);
            ViewData["LitterId"] = new SelectList(_context.Litters.Where(m => m.KennelId == userKennelId), "LitterId", "Name", puppy.LitterId);
            return View(puppy);
        }

        // GET: Puppies/Delete/5
        [Authorize(Roles = SD.Role_User_Breeder)]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var puppy = await _context.Puppies
                .Include(p => p.Dog)
                .Include(p => p.Litter)
                .FirstOrDefaultAsync(m => m.PuppyId == id);
            if (puppy == null || puppy.Litter.KennelId != GetUserKennel().KennelId)
            {
                return NotFound();
            }

            return View(puppy);
        }

        // POST: Puppies/Delete/5
        [Authorize(Roles = SD.Role_User_Breeder)]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var puppy = await _context.Puppies
                .Include(p => p.Dog)
                .Include(p => p.Litter)
                .FirstOrDefaultAsync(m => m.PuppyId == id);
            _context.Puppies.Remove(puppy);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(MyPuppies));
        }

        private bool PuppyExists(int id)
        {
            return _context.Puppies.Any(e => e.PuppyId == id);
        }

        // Saját metódusaim
        private string GetUserId()
        {
            return User.FindFirstValue(ClaimTypes.NameIdentifier);
        }

        private Kennel GetUserKennel()
        {
            string id = GetUserId();
            var userKennel = _context.Kennels.FirstOrDefault(m => m.ApplicationUserId == id);
            return userKennel;
        }

        private IQueryable<Litter> GetUserLitters()
        {
            int id = GetUserKennel().KennelId;

            var userLitters = _context.Litters
                .Include(l => l.Father)
                .Include(l => l.Kennel)
                .Include(l => l.Mother)
                .Where(m => m.KennelId == id);

            return userLitters;
        }
        private IQueryable<Puppy> GetUserPuppies()
        {
            int id = GetUserKennel().KennelId;

            var userPuppies = _context.Puppies
                .Include(p => p.Dog)
                .Include(p => p.Litter)
                .Where(m => m.Litter.KennelId == id);

            return userPuppies;
        }
    }
}

Mykennel/Views/Shared/Oops.cshtml
@{
    ViewData["Title"] = "Error" + @ViewData["ErrorCode"];
}

<div class="row h-100">
    <div class="text-center mx-auto">
        <h1 class="errorcode">
            <span>@ViewData["ErrorCode"].ToString()[0]</span>
            <span class="mycolor">@ViewData["ErrorCode"].ToString()[1]</span>
            <span>@ViewData["ErrorCode"].ToString()[2]</span>
        </h1>
        @if (ViewData["ErrorCode"].Equals("404"))
        {
            <h2 class="errorcodetext">Oops! Page not found.</h2>
        }
        else
        {
            <h2 class="errorcodetext">Oops! Something went wrong.</h2>
        }
    </div>
</div>

Mykennel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="robots" content="noindex" />
    <title>@ViewData["Title"] - Mykennel</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    @if (ViewContext?.ActionDescriptor?.RouteValues["area"] != null && ViewContext?.ActionDescriptor?.RouteValues["area"].ToString() == "Admin")
    {
        <link rel="stylesheet" href="~/css/BootstrapDark/bootstrap.min.css" />
    }

    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <partial name="_Menu" />

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Mykennel - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
        @await RenderSectionAsync("Scripts", required: false)
    </body>
</html>

Mykennel/Views/Shared/_Menu.cshtml
@using Mykennel.Utility

<header>
    <nav class="navbar navbar-expand-md navbar-toggleable-md navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mykennel</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="navbar-collapse collapse d-md-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">

                    <!-- Lekérdezi milyen area-ban vagyunk, majd szerepkör szerint jelenít meg menüpontokat-->
                    @if (ViewContext?.ActionDescriptor?.RouteValues["area"] == null)
                    {
                        @if (ViewContext.RouteData.Values["action"].ToString() != "Details")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Kennels" asp-action="Index">Kennels</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Litters" asp-action="Index">Litters</a>
                            </li>
                        }

                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Home" asp-action="Index">Admin</a>
                            </li>
                        }

                        @if (User.IsInRole(SD.Role_User_Breeder))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    My kennel
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="" asp-controller="Kennels" asp-action="Settings">Kennel settings</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Dogs" asp-action="MyDogs">My dogs</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Litters" asp-action="MyLitters">My litters</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Puppies" asp-action="MyPuppies">My puppies</a>
                                </div>
                            </li>
                        }
                    }

                    @if (ViewContext?.ActionDescriptor?.RouteValues["area"] != null && ViewContext?.ActionDescriptor?.RouteValues["area"].ToString() == "Admin")
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Content Management
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Users" asp-action="Index">Users</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Kennels" asp-action="Index">Kennels</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Breeds" asp-action="Index">Breeds</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Countries" asp-action="Index">Countries</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="btn btn-danger" asp-area="Admin" asp-controller="Tester" asp-action="Index">Tester</a>
                        </li>
                    }

                    @if (ViewBag.FindAdmin == false) {
                <li class="nav-item">
                    <a class="btn btn-danger" asp-action="CreateAdmin">Create Admin</a>
                </li>
                    }

                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>
</header>